trigger:
  - main  

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - checkout: self  
          - script: echo 
            displayName: 'Build App'

  - stage: Test
    jobs:
      - job: TestJob
        steps:
          - script: echo 
            displayName: 'Run Mock Tests'

  - stage: Deploy
    jobs:
      - job: DeployJob
        steps:
          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'AzureVMServiceConnection'  # create this in Azure DevOps
              sourceFolder: '$(Build.SourcesDirectory)/app'  # adjust to match your folder
              contents: '**'
              targetFolder: '/var/www/html'
